# 基础配置
server:
  port: ${PORT:8080}
# 数据源配置
spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.99.98.115:3306/dzhn_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password:  Develop123@
        druid:
          initial-size: 5 #连接池初始化大小
          min-idle: 10 #最小空闲连接数
          max-active: 20 #最大连接数
          web-stat-filter:
              exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
          stat-view-servlet: #访问监控网页的登录用户名和密码
              login-username: druid
              ogin-password: druid
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    timeout: 6000  # 连接超时时长（毫秒）
#    pool:
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 5       # 连接池中的最小空闲连接

## Mybatis 配置
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapping/*.xml
#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/lanpower/core/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.zhsw.rabbitmqaccess.entity
#  typeEnumsPackage: com.zhsw.rabbitmqaccess.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: input
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false

customer:
  isLoadCustSysDict: false   # 启动时是否加载数据字典表中数据到 Redis 缓存
