# 基础配置
server:
  port: ${PORT:60001}
# 数据源配置
spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/starter?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: 123456
        druid:
             validation-query: SELECT 1 FROM DUAL
             initial-size: 10
             max-active: 100
             min-idle: 10
             max-wait: 60000
             pool-prepared-statements: true
             max-open-prepared-statements: 100
             time-between-eviction-runs-millis: 60000
             min-evictable-idle-time-millis: 300000
             test-while-idle: true
             test-on-borrow: false
             test-on-return: false
             filters: stat,wall
             share-prepared-statements: true
             stat-view-servlet:
                url-pattern: /druid/*
                reset-enable: false
                loginUsername: admin
                loginPassword: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接

## Mybatis 配置
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapping/*.xml
#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/framework/core/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.zhsw.rabbitmqaccess.entity
#  typeEnumsPackage: com.zhsw.rabbitmqaccess.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: input
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false

customer:
  isLoadCustSysDict: true   # 启动时是否加载数据字典表中数据到 Redis 缓存
